application: djangomezz
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.4"
- name: PIL
  version: "1.1.7"

builtins:
- django_wsgi: on

env_variables:
    DJANGO_SETTINGS_MODULE: 'mywebsite.settings'

handlers:
- url: /static/admin
  static_dir: mywebsite/static/admin/

- url: /static
  static_dir: mywebsite/static/